/* Generated By:JavaCC: Do not edit this line. ParserJCCConstants.java */
package Analizador;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserJCCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TIPO = 1;
  /** RegularExpression Id. */
  int IDPREGUNTA = 2;
  /** RegularExpression Id. */
  int ETIQUETA = 3;
  /** RegularExpression Id. */
  int SUGERIR = 4;
  /** RegularExpression Id. */
  int CODIGO_PRE = 5;
  /** RegularExpression Id. */
  int CODIGO_POST = 6;
  /** RegularExpression Id. */
  int RESTRINGIR = 7;
  /** RegularExpression Id. */
  int RESTRINGIRMSN = 8;
  /** RegularExpression Id. */
  int REQUERIDO = 9;
  /** RegularExpression Id. */
  int REQUERIDOMSN = 10;
  /** RegularExpression Id. */
  int PREDETERMINADO = 11;
  /** RegularExpression Id. */
  int APLICABLE = 12;
  /** RegularExpression Id. */
  int LECTURA = 13;
  /** RegularExpression Id. */
  int CALCULO = 14;
  /** RegularExpression Id. */
  int REPETICION = 15;
  /** RegularExpression Id. */
  int MULTIMEDIA = 16;
  /** RegularExpression Id. */
  int APARIENCIA = 17;
  /** RegularExpression Id. */
  int PARAMETRO = 18;
  /** RegularExpression Id. */
  int NOMBRE_LISTA = 19;
  /** RegularExpression Id. */
  int NOMBRE = 20;
  /** RegularExpression Id. */
  int TITULO_FORMULARIO = 21;
  /** RegularExpression Id. */
  int IDFORM = 22;
  /** RegularExpression Id. */
  int ESTILO = 23;
  /** RegularExpression Id. */
  int IMPORTAR = 24;
  /** RegularExpression Id. */
  int CODIGO_PRINCIPAL = 25;
  /** RegularExpression Id. */
  int CODIGO_GLOBAL = 26;
  /** RegularExpression Id. */
  int ENCUESTA = 27;
  /** RegularExpression Id. */
  int OPCIONES = 28;
  /** RegularExpression Id. */
  int CONFIGURACION = 29;
  /** RegularExpression Id. */
  int ENTERO = 30;
  /** RegularExpression Id. */
  int DECIMAL = 31;
  /** RegularExpression Id. */
  int RANGO = 32;
  /** RegularExpression Id. */
  int CONDICION = 33;
  /** RegularExpression Id. */
  int FECHA = 34;
  /** RegularExpression Id. */
  int HORA = 35;
  /** RegularExpression Id. */
  int FECHAHORA = 36;
  /** RegularExpression Id. */
  int SELECCION_UNO = 37;
  /** RegularExpression Id. */
  int SELECCION_MULTIPLE = 38;
  /** RegularExpression Id. */
  int NOTA = 39;
  /** RegularExpression Id. */
  int FICHERO = 40;
  /** RegularExpression Id. */
  int CALCULAR = 41;
  /** RegularExpression Id. */
  int INICIAR_AGRUPACION = 42;
  /** RegularExpression Id. */
  int FINALIZAR_AGRUPACION = 43;
  /** RegularExpression Id. */
  int INICIAR_CICLO = 44;
  /** RegularExpression Id. */
  int FINALIZAR_CICLO = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"tipo\"",
    "\"idpregunta\"",
    "\"etiqueta\"",
    "\"sugerir\"",
    "\"codigo_pre\"",
    "\"codigo_post\"",
    "\"restringir\"",
    "\"restringirmsn\"",
    "\"requerido\"",
    "\"requeridomsn\"",
    "\"predeterminado\"",
    "\"aplicable\"",
    "\"lectura\"",
    "\"calculo\"",
    "\"repeticion\"",
    "\"multimedia\"",
    "\"apariencia\"",
    "\"parametro\"",
    "\"nombre_lista\"",
    "\"nombre\"",
    "\"titulo_formulario\"",
    "\"idform\"",
    "\"estilo\"",
    "\"importar\"",
    "\"codigo_principal\"",
    "\"codigo_global\"",
    "\"encuesta\"",
    "\"opciones\"",
    "\"configuracion\"",
    "\"entero\"",
    "\"decimal\"",
    "\"rango\"",
    "\"condicion\"",
    "\"fecha\"",
    "\"hora\"",
    "\"fechahora\"",
    "\"seleccion_uno\"",
    "\"seleccion_multiple\"",
    "\"nota\"",
    "\"fichero\"",
    "\"calcular\"",
    "\"iniciar agrupacion\"",
    "\"finalizar agrupacion\"",
    "\"iniciar ciclo\"",
    "\"finalizar ciclo\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
  };

}
